import BoardContainer from '@/components/BoardContainer';
import Header from '@/components/Header';

import TaskChoices from '@/components/TaskChoices';
import TopCards from '@/components/TopCards';
import Head from 'next/head';

export default function Home() {
	return (
		<>
			<Head>
				<title>Accolades - Token Board</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link
					rel='icon'
					href='/favicon.ico'
				/>
			</Head>
			<main className='bg-gray-100 min-h-screen'>
				<Header />
				<TopCards/>
				<div className='grid lg:grid-cols-3 gap-4 p-4'>
					<BoardContainer />
				
				</div>
			</main>
		</>
	);
}
